[
    { "name": "What’s one thing you’ve always wanted to try but haven’t yet?" },
    { "name": "What’s the best advice you’ve ever received?" },
    { "name": "If you could instantly master any skill, what would it be?" },
    { "name": "What’s a small moment from your childhood that stuck with you?" },
    { "name": "What does a perfect weekend look like for you?" },
    { "name": "What’s one job you’d be terrible at?" },
    { "name": "If you could trade jobs with anyone for a day, who would it be and why?" },
    { "name": "What's your favorite way to stay productive?" },
    { "name": "What’s something work-related you’re proud of?" },
    { "name": "If money wasn’t a factor, what would you do for work?" },
    { "name": "What book has had the biggest impact on your life?" },
    { "name": "Which fictional character do you most relate to?" },
    { "name": "Do you prefer physical books, e-books, or audiobooks?" },
    { "name": "What’s a book you always recommend?" },
    { "name": "What book do you wish you could read again for the first time?" },
    { "name": "What’s your comfort movie or show you always go back to?" },
    { "name": "If you could live in any movie universe, which one would it be?" },
    { "name": "What’s a movie that surprised you (in a good way)?" },
    { "name": "Who is your favorite movie villain or anti-hero?" },
    { "name": "What’s a movie that made you cry (or almost cry)?" },
    { "name": "If you could have dinner with any historical figure, who would it be and why?" },
    { "name": "What’s your go-to karaoke song?" },
    { "name": "If you could instantly master one skill, what would it be?" },
    { "name": "What’s the most unusual food you’ve ever tried?" },
    { "name": "If you could live in any fictional universe, which one would you choose?" },
    { "name": "What’s your guilty pleasure TV show or movie?" },
    { "name": "If you had a time machine, would you go to the past or the future?" },
    { "name": "What’s a weird or funny talent you have?" },
    { "name": "If you could swap lives with a celebrity for a day, who would it be?" },
    { "name": "What’s the best prank you’ve ever played on someone?" },
    { "name": "If you could have any job in the world for one day, what would it be?" },
    { "name": "What’s the best piece of career advice you’ve ever received?" },
    { "name": "How do you stay motivated during a tough workday?" },
    { "name": "If you had an unlimited budget for one work-related gadget, what would you buy?" },
    { "name": "What’s the funniest or weirdest thing that’s ever happened to you at work?" },
    { "name": "What’s a productivity hack you swear by?" },
    { "name": "If you had to describe your job using only a movie title, what would it be?" },
    { "name": "What’s your favorite way to unwind after a long day?" },
    { "name": "Would you rather work remotely from the beach or from a cabin in the mountains?" },
    { "name": "If you could only use one app for work, which one would you pick?" },
    { "name": "What’s the best trip you’ve ever been on?" },
    { "name": "If you could teleport to any place in the world right now, where would you go?" },
    { "name": "What’s your dream travel destination?" },
    { "name": "Have you ever had a travel experience that didn’t go as planned?" },
    { "name": "What’s the most adventurous thing you’ve ever done?" },
    { "name": "If you had to move to another country tomorrow, where would it be?" },
    { "name": "What’s one place you think everyone should visit at least once?" },
    { "name": "What’s your funniest or most embarrassing travel story?" },
    { "name": "If you could do a road trip with any three people (dead or alive), who would you choose?" },
    { "name": "Would you rather explore deep space or the bottom of the ocean?" },
    { "name": "What’s your ultimate comfort food?" },
    { "name": "If you had to eat only one cuisine for the rest of your life, what would it be?" },
    { "name": "What’s the strangest food combination you actually enjoy?" },
    { "name": "If you could create a new flavor of ice cream, what would it be?" },
    { "name": "Do you prefer cooking at home or eating out?" },
    { "name": "What’s the best meal you’ve ever had?" },
    { "name": "If you could only drink one type of beverage (besides water) for the rest of your life, what would it be?" },
    { "name": "Sweet or savory snacks?" },
    { "name": "What’s one food you can’t stand?" },
    { "name": "If you could open your own restaurant, what kind of food would you serve?" },
    { "name": "If you could have a superpower, what would it be?" },
    { "name": "What’s your favorite way to spend a lazy Sunday?" },
    { "name": "If your life were a book, what would the title be?" },
    { "name": "What’s the weirdest fact you know?" },
    { "name": "If you could swap places with any fictional character for a week, who would it be?" },
    { "name": "What’s the most unexpected or unusual hobby you’ve tried?" },
    { "name": "Would you rather always be 10 minutes early or always be 10 minutes late?" },
    { "name": "What’s one thing on your bucket list you haven’t done yet?" },
    { "name": "If you could bring back any extinct animal, which one would it be?" },
    { "name": "If you could have a conversation with your future self, what’s one question you’d ask?" }
  ]